# Generated by Django 3.2.7 on 2021-09-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro'), ('Outro', 'Outro')], max_length=8),
        ),
    ]
